### ISSUE TITLE
kong_nginx_http_current_connections gauge but seem cumulative

### ISSUE THREAD

**Issue by christianlafleur** [Kong/kong-plugin-prometheus#41]
kong_nginx_http_current_connections is gauge Why state accepted / handled / total seem to be cumulative ?
kong is 0.14.1

metrics sample :
# TYPE kong_nginx_http_current_connections gauge
kong_nginx_http_current_connections{state="accepted"} 45662
kong_nginx_http_current_connections{state="active"} 2
kong_nginx_http_current_connections{state="handled"} 45662
kong_nginx_http_current_connections{state="reading"} 0
kong_nginx_http_current_connections{state="total"} 49089
kong_nginx_http_current_connections{state="waiting"} 1
kong_nginx_http_current_connections{state="writing"} 1

**Comment by hbagdi** [comment]
Yes, they are cummilative and they should be counters and not gauges.

The reason they are gauges is an implementation limitation.
In the underlying library, counters can only be incremented and not set, meaning, a counter with value of 42 can be incremented by 10, making the value 52 but it cannot be set to 52.

In this case, we do not know the difference (10) but know the value (52), hence we use Gauge:
https://github.com/Kong/kong-plugin-prometheus/blob/master/kong/plugins/prometheus/exporter.lua#L107

Are you facing any functional limitation due to this?

**Comment by christianlafleur** [comment]
Thanks for the clarification, no we don't facing any problem with this.
